
### --------------CREATION TESTS-------------- ###

### submit new record to the Database

POST http://localhost:5273/api/create/record
Content-Type: application/json

{
    "account": "WellsFargo",
    "type": "income",
    "amount": "1.50",
    "category": "household",
    "area": "groceries",
    "date": "08/05/2023", 
    "user": "64da703566eec4e5572af1de"
}

### submit new account to the Database

POST http://localhost:5273/api/create/account
Content-Type: application/json

{
    "account": "WellsFargo",
    "currency": "USD",
    "amount": "30.00",
    "user": "64da703566eec4e5572af1de"
}

### submit new goal to the Database

POST http://localhost:5273/api/create/goal
Content-Type: application/json

{
    "category": "household",
    "area": "groceries",
    "amount": "9000",
    "user": "64da703566eec4e5572af1de"
}

### --------------FETCHING TESTS-------------- ###
### fetch current value of money

GET http://localhost:5273/api/current?user=64da703566eec4e5572af1de

### fetch record documents sorted by date

GET http://localhost:5273/api/fetch/record
Content-Type: application/json

{
    "userID": "64da703566eec4e5572af1de"
}

### fetch account documents sorted by date

GET http://localhost:5273/api/fetch/account
Content-Type: application/json

{
    "userID": "64da703566eec4e5572af1de"
}

### fetch goal documents sorted by date

GET http://localhost:5273/api/fetch/goal
Content-Type: application/json

{
    "userID": "64da703566eec4e5572af1de"
}

### --------------DELETION TESTS-------------- ###


### delete record document

DELETE http://localhost:5273/api/delete/record
Content-Type: application/json

{
    "recordID": "64da703566eec4e5572af1de"
}


### Login User
POST http://localhost:5273/api/login
Content-Type: application/json

{
    "username": "joey",
    "password": "f"
}


### Register User
POST http://localhost:5273/api/register_user
Content-Type: application/json

{
    "username": "joey",
    "email": "god@gmail.com",
    "password": "f"
}