
### --------------CREATION TESTS-------------- ###

### submit new record to the Database

POST http://localhost:5273/api/create/record
Content-Type: application/json

{
    "account": "WellsFargo",
    "type": "expense",
    "amount": "30.00",
    "category": "household",
    "area": "groceries",
    "date": "08/05/2023", 
    "user": "64d3d7e48f3aee818fc95876"
}

### submit new account to the Database

POST http://localhost:5273/api/create/account
Content-Type: application/json

{
    "account": "WellsFargo",
    "currency": "USD",
    "amount": "30.00",
    "user": "64d3d7e48f3aee818fc95876"
}

### submit new goal to the Database

POST http://localhost:5273/api/create/goal
Content-Type: application/json

{
    "category": "household",
    "area": "groceries",
    "amount": "9000",
    "user": "64d3d7e48f3aee818fc95876"
}

### --------------FETCHING TESTS-------------- ###

### fetch record documents sorted by date

GET http://localhost:5273/api/fetch/record
Content-Type: application/json

{
    "userID": "64d3d7e48f3aee818fc95876"
}

### fetch account documents sorted by date

GET http://localhost:5273/api/fetch/account
Content-Type: application/json

{
    "userID": "64d3d7e48f3aee818fc95876"
}

### fetch goal documents sorted by date

GET http://localhost:5273/api/fetch/goal
Content-Type: application/json

{
    "userID": "64d3d7e48f3aee818fc95876"
}

### --------------DELETION TESTS-------------- ###


### delete record document

DELETE http://localhost:5273/api/delete/record
Content-Type: application/json

{
    "recordID": "64d41ab8679ac5d31f2ca0ae"
}