### --------------CREATION TESTS-------------- ###

### submit new record to the Database

POST http://localhost:5273/api/create/record
Content-Type: application/json

{
    "account": "CitiBanamex",
    "type": "income",
    "amount": "12500",
    "category": "household",
    "area": "payment",
    "date": "08/05/2023", 
    "user": "64e6697d84508dbcbcd73ced"
}

### submit new account to the Database

POST http://localhost:5273/api/create/account
Content-Type: application/json

{
    "account": "CitiBanamex",
    "currency": "MXN",
    "startingAmount": "30.00",
    "user": "64e6697d84508dbcbcd73ced"
}

### submit new goal to the Database

POST http://localhost:5273/api/create/goal
Content-Type: application/json

{
    "category": "household",
    "area": "groceries",
    "amount": "9000",
    "user": "64da703566eec4e5572af1de"
}